//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamosServicios.usuariosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/UsuariosDMS.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="usuariosWS.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        PrestamosServicios.usuariosWS.Usuario CrearUsuario(string codigo, string correo, string nombre, int tipo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> CrearUsuarioAsync(string codigo, string correo, string nombre, int tipo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        PrestamosServicios.usuariosWS.Usuario ObtenerUsuario(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> ObtenerUsuarioAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        PrestamosServicios.usuariosWS.Usuario ModificarUsuario(string codigo, string correo, string nombre, int tipo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> ModificarUsuarioAsync(string codigo, string correo, string nombre, int tipo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        void EliminarUsuario(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuarioResponse")]
        PrestamosServicios.usuariosWS.Usuario[] ListarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario[]> ListarUsuarioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : PrestamosServicios.usuariosWS.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<PrestamosServicios.usuariosWS.IUsuarios>, PrestamosServicios.usuariosWS.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PrestamosServicios.usuariosWS.Usuario CrearUsuario(string codigo, string correo, string nombre, int tipo, string password) {
            return base.Channel.CrearUsuario(codigo, correo, nombre, tipo, password);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> CrearUsuarioAsync(string codigo, string correo, string nombre, int tipo, string password) {
            return base.Channel.CrearUsuarioAsync(codigo, correo, nombre, tipo, password);
        }
        
        public PrestamosServicios.usuariosWS.Usuario ObtenerUsuario(string codigo) {
            return base.Channel.ObtenerUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> ObtenerUsuarioAsync(string codigo) {
            return base.Channel.ObtenerUsuarioAsync(codigo);
        }
        
        public PrestamosServicios.usuariosWS.Usuario ModificarUsuario(string codigo, string correo, string nombre, int tipo, string password) {
            return base.Channel.ModificarUsuario(codigo, correo, nombre, tipo, password);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario> ModificarUsuarioAsync(string codigo, string correo, string nombre, int tipo, string password) {
            return base.Channel.ModificarUsuarioAsync(codigo, correo, nombre, tipo, password);
        }
        
        public void EliminarUsuario(string codigo) {
            base.Channel.EliminarUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(string codigo) {
            return base.Channel.EliminarUsuarioAsync(codigo);
        }
        
        public PrestamosServicios.usuariosWS.Usuario[] ListarUsuario() {
            return base.Channel.ListarUsuario();
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.usuariosWS.Usuario[]> ListarUsuarioAsync() {
            return base.Channel.ListarUsuarioAsync();
        }
    }
}
