//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPrestamos.equiposWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipo", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Equipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="equiposWS.IEquipos")]
    public interface IEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        TestPrestamos.equiposWS.Equipo CrearEquipo(string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> CrearEquipoAsync(string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        TestPrestamos.equiposWS.Equipo ObtenerEquipo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> ObtenerEquipoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        TestPrestamos.equiposWS.Equipo ModificarEquipo(int codigo, string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> ModificarEquipoAsync(int codigo, string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        void EliminarEquipo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        System.Threading.Tasks.Task EliminarEquipoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        TestPrestamos.equiposWS.Equipo[] ListarEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo[]> ListarEquiposAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquiposChannel : TestPrestamos.equiposWS.IEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquiposClient : System.ServiceModel.ClientBase<TestPrestamos.equiposWS.IEquipos>, TestPrestamos.equiposWS.IEquipos {
        
        public EquiposClient() {
        }
        
        public EquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestPrestamos.equiposWS.Equipo CrearEquipo(string serie, string modelo, string estado) {
            return base.Channel.CrearEquipo(serie, modelo, estado);
        }
        
        public System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> CrearEquipoAsync(string serie, string modelo, string estado) {
            return base.Channel.CrearEquipoAsync(serie, modelo, estado);
        }
        
        public TestPrestamos.equiposWS.Equipo ObtenerEquipo(int codigo) {
            return base.Channel.ObtenerEquipo(codigo);
        }
        
        public System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> ObtenerEquipoAsync(int codigo) {
            return base.Channel.ObtenerEquipoAsync(codigo);
        }
        
        public TestPrestamos.equiposWS.Equipo ModificarEquipo(int codigo, string serie, string modelo, string estado) {
            return base.Channel.ModificarEquipo(codigo, serie, modelo, estado);
        }
        
        public System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo> ModificarEquipoAsync(int codigo, string serie, string modelo, string estado) {
            return base.Channel.ModificarEquipoAsync(codigo, serie, modelo, estado);
        }
        
        public void EliminarEquipo(int codigo) {
            base.Channel.EliminarEquipo(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarEquipoAsync(int codigo) {
            return base.Channel.EliminarEquipoAsync(codigo);
        }
        
        public TestPrestamos.equiposWS.Equipo[] ListarEquipos() {
            return base.Channel.ListarEquipos();
        }
        
        public System.Threading.Tasks.Task<TestPrestamos.equiposWS.Equipo[]> ListarEquiposAsync() {
            return base.Channel.ListarEquiposAsync();
        }
    }
}
